export const ADD_TASK = 'TASK/ADD_TASK';
export const DELETE_TASK = 'TASK/DELETE_TASK';

export const ENABLE_IS_COMPLETE_STATUS = 'TASK/ENABLE_IS_COMPLETE_STATUS';
export const DISABLE_IS_COMPLETE_STATUS = 'TASK/DISABLE_IS_COMPLETE_STATUS';
